# Generated by Django 4.2.30 on 2026-06-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_equipement",
                    models.CharField(
                        choices=[
                            ("uniforme_ete", "Uniforme été"),
                            ("uniforme_hiver", "Uniforme hiver"),
                            ("veste", "Veste"),
                            ("pantalon", "Pantalon"),
                            ("chemise", "Chemise"),
                            ("complet", "Tenue complète"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tour_poitrine",
                    models.FloatField(verbose_name="Tour de poitrine (cm)"),
                ),
                ("tour_taille", models.FloatField(verbose_name="Tour de taille (cm)")),
                (
                    "tour_hanches",
                    models.FloatField(verbose_name="Tour de hanches (cm)"),
                ),
                ("epaules", models.FloatField(verbose_name="Largeur épaules (cm)")),
                ("manche", models.FloatField(verbose_name="Longueur manche (cm)")),
                ("entrejambe", models.FloatField(verbose_name="Entrejambe (cm)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("en_production", "En production"),
                            ("pret", "Prêt"),
                            ("livre", "Livré"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "notes_admin",
                    models.TextField(blank=True, verbose_name="Notes admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de mesure",
                "verbose_name_plural": "Fiches de mesure",
                "ordering": ["-created_at"],
            },
        ),
    ]
