# Generated by Django 4.2.30 on 2026-06-29 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="rempli_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiches_remplies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rempli par",
            ),
        ),
    ]
