# Generated by Django 4.2.30 on 2026-07-07 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurements', '0002_measurement_rempli_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourEffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equipement', models.CharField(choices=[('uniforme_ete', 'Uniforme été'), ('uniforme_hiver', 'Uniforme hiver'), ('veste', 'Veste'), ('pantalon', 'Pantalon'), ('chemise', 'Chemise'), ('complet', 'Tenue complète')], max_length=50)),
                ('quantite', models.IntegerField()),
                ('motif', models.CharField(choices=[('destruction', 'Destruction'), ('perte', 'Perte'), ('usure', 'Usure normale'), ('autre', 'Autre')], default='destruction', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Retour d'effet",
                'verbose_name_plural': "Retours d'effets",
                'ordering': ['-created_at'],
            },
        ),
    ]
