# Generated by Django 4.2.30 on 2026-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("agent", "Agent"),
                    ("admin", "Administrateur"),
                    ("technicien", "Technicien"),
                    ("secretaire", "Secrétaire"),
                ],
                default="agent",
                max_length=20,
            ),
        ),
    ]
