# Generated by Django 4.2.30 on 2026-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("uniforme_ete", "Uniforme été"),
                            ("uniforme_hiver", "Uniforme hiver"),
                            ("veste", "Veste"),
                            ("pantalon", "Pantalon"),
                            ("chemise", "Chemise"),
                            ("complet", "Tenue complète"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("XXXL", "XXXL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "min_threshold",
                    models.IntegerField(default=5, verbose_name="Seuil minimum"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article en stock",
                "verbose_name_plural": "Stock",
                "ordering": ["category", "size"],
            },
        ),
    ]
