# Generated by Django 4.2.30 on 2026-07-02 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("livraison_fournisseur", "Livraison fournisseur"),
                            ("retour", "Retour article"),
                            ("production", "Mise en production"),
                            ("perte", "Perte / Détérioration"),
                            ("inventaire", "Correction inventaire"),
                            ("autre", "Autre"),
                        ],
                        max_length=40,
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité")),
                ("quantity_before", models.IntegerField(verbose_name="Qté avant")),
                ("quantity_after", models.IntegerField(verbose_name="Qté après")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="stock.stockitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-created_at"],
            },
        ),
    ]
